# Site configuration
title: HA-Lizard RPM Repository
description: Official repository for HA-Lizard, providing tools for high availability in Citrix XenServer environments.
baseurl: "/repo"
url: "https://ha-liza.github.io/repo" # Replace with your GitHub Pages URL

# Author information
author:
  name: HA-Lizard Team
  email: contact@halizard.com
  url: https://halizard.com/

theme: minima

# Social links
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/ha-lizard" }
    - { platform: twitter, user_url: "https://twitter.com/halizard" }
    - { platform: telegram, user_url: "@ha-lizard" }

# Plugins
plugins:
  - jekyll-feed # RSS feeds for blog posts
  - jekyll-sitemap # Generates a sitemap
  - jekyll-seo-tag # Adds SEO metadata

# TODO: google analytics ?
# google_analytics: UA-NNNNNNNN-N

# Include additional directories
include:
  - _data
  - rpms
  - stable
  - unstable
  - gpg

# Exclude these from the output
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
